"""User Table Added

Revision ID: 17741c32eaad
Revises: a2c0111f6c5b
Create Date: 2022-08-02 07:55:49.373589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17741c32eaad"
down_revision = "a2c0111f6c5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ApplicationUser",
        sa.Column("ID", sa.Integer(), nullable=False),
        sa.Column("First", sa.String(length=50), nullable=False),
        sa.Column("Last", sa.String(length=50), nullable=False),
        sa.Column("Email", sa.String(length=100), nullable=False),
        sa.Column("PrimaryPhone", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("ID"),
    )
    op.create_index(
        op.f("ix_ApplicationUser_ID"), "ApplicationUser", ["ID"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ApplicationUser_ID"), table_name="ApplicationUser")
    op.drop_table("ApplicationUser")
    # ### end Alembic commands ###
