"""first table

Revision ID: bb3fd19ac45a
Revises: 
Create Date: 2022-07-31 13:06:29.590552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3fd19ac45a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projects',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=100), nullable=False),
    sa.Column('URL', sa.String(length=500), nullable=False),
    sa.Column('First', sa.String(length=50), nullable=True),
    sa.Column('Last', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Projects_ID'), 'Projects', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Projects_ID'), table_name='Projects')
    op.drop_table('Projects')
    # ### end Alembic commands ###
