"""adding user id column

Revision ID: d89985f1b573
Revises: 17741c32eaad
Create Date: 2022-08-02 09:25:32.337774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d89985f1b573"
down_revision = "17741c32eaad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Projects", sa.Column("UserID", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "Projects", "ApplicationUser", ["UserID"], ["ID"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Projects", type_="foreignkey")
    op.drop_column("Projects", "UserID")
    # ### end Alembic commands ###
